### Load GPU

In [50]:
import torch

In [51]:
!nvidia-smi

Wed Nov  2 17:33:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    30W /  70W |   1298MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Load Multinews Dataset

In [52]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [53]:
from datasets import load_dataset
dataset = load_dataset("multi_news")

  0%|          | 0/3 [00:00<?, ?it/s]

In [54]:
train_doc, train_summary = dataset['train']['document'], dataset['train']['summary']

### Split sentences

In [55]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [56]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [57]:
from nltk.tokenize import sent_tokenize, word_tokenize
#for i in range(1):
import time
start = time
sentences = sent_tokenize(train_doc[0])
print(len(sentences))


17


### bert embedding

In [58]:
## Install libraries
!pip install sentence-transformers
import os
import pandas as pd
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distilbert-base-nli-mean-tokens')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
embedding = []
for sentence in sentences:
  embedding.append(model.encode(sentence, show_progress_bar=True))
embedding

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[array([-5.02319276e-01, -9.92897227e-02,  5.71659386e-01, -1.33347082e+00,
         5.62998578e-02, -1.60735473e-01,  6.53897464e-01,  8.26587558e-01,
        -1.38707590e+00, -8.90202343e-01,  7.04020441e-01,  9.39428926e-01,
         5.26804149e-01,  3.41349721e-01,  5.76394498e-01, -5.51939249e-01,
        -4.83390242e-01, -6.52575433e-01,  3.57395932e-02, -6.58097863e-01,
         2.24945754e-01, -6.24776632e-02,  6.61858380e-01,  6.66128159e-01,
        -6.99111581e-01, -7.75790513e-01,  4.50718254e-01,  3.42276186e-01,
        -1.23962484e-01,  2.63063967e-01,  1.88242823e-01, -6.59477115e-01,
        -3.00768346e-01,  1.32964659e+00,  1.63750738e-01, -1.06183931e-01,
        -3.84818166e-01,  6.45910084e-01, -4.66269463e-01, -2.65844226e-01,
         8.17397833e-01, -1.98148251e-01,  6.00458443e-01, -3.18204761e-01,
        -9.83485222e-01,  1.16002560e-01, -4.70181316e-01,  9.33705736e-03,
        -1.74287641e+00, -6.28044128e-01, -6.71770394e-01,  3.93151283e-01,
         5.4

In [11]:
len(embedding)

17

hdbscan

In [59]:
!pip install joblib==1.1.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [60]:
!pip install hdbscan --no-build-isolation --no-binary :all:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [61]:
import hdbscan
clusterer = hdbscan.HDBSCAN(min_cluster_size=2, gen_min_span_tree=True)
clusterer.fit(embedding)
print(clusterer.labels_)

[ 1  1 -1 -1 -1  1  2 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1  2 -1
 -1 -1 -1 -1 -1  0 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  2 -1 -1 -1
 -1 -1 -1]


In [15]:

clustered_sentences = [[] for i in range(2)]
for sentence_id, cluster_id in enumerate(clusterer.labels_):
    clustered_sentences[cluster_id].append(sentences[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['||||| Employers pulled back sharply on hiring last month, a reminder that the U.S. economy may not be growing fast enough to sustain robust job growth.', 'The unemployment rate dipped, but mostly because more Americans stopped looking for work.']

Cluster  2
['National Archives \n \n Yes, it’s that time again, folks.', 'It’s the first Friday of the month, when for one ever-so-brief moment the interests of Wall Street, Washington and Main Street are all aligned on one thing: Jobs.', 'A fresh update on the U.S. employment situation for January hits the wires at 8:30 a.m. New York time offering one of the most important snapshots on how the economy fared during the previous month.', 'Expectations are for 203,000 new jobs to be created, according to economists polled by Dow Jones Newswires, compared to 227,000 jobs added in February.', 'The unemployment rate is expected to hold steady at 8.3%.', 'Here at MarketBeat HQ, we’ll be offering color commentary before and after the da

In [74]:
hdb_num_cluster_all = []
hdb_cluster_assignment_all = []
for i in range(10):
  sentences = sent_tokenize(train_doc[i]) #split sentences
  embedding = embedding_all[i] #get embedding 
  
  cluster_assignment = hdbscan.HDBSCAN(min_cluster_size=2, gen_min_span_tree=True).fit(embedding).labels_
  num_clusters = len(np.unique(cluster_assignment))
  
  hdb_num_cluster_all.append(num_clusters)
  hdb_cluster_assignment_all.append(cluster_assignment)

In [75]:
hdb_num_cluster_all

[3, 4, 5, 3, 3, 3, 3, 3, 5, 4]

In [71]:
hdb_cluster_assignment_all

[array([-1, -1,  1, -1, -1, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1,  1, -1]),
 array([ 1,  0,  0,  1,  1,  2, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1,
        -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  0,
        -1,  1,  0, -1,  1,  2,  1, -1,  1]),
 array([-1,  2,  2, -1,  2,  2,  2,  2,  2,  1,  0,  2,  2,  2, -1,  2,  2,
        -1,  0,  2, -1,  2, -1, -1,  2, -1,  1, -1,  2,  1, -1, -1, -1,  2,
        -1, -1,  2,  2,  2,  2,  2, -1,  3, -1, -1,  2,  2,  2,  3,  2,  2,
        -1, -1,  3, -1,  2,  2,  2, -1, -1, -1,  2, -1,  2, -1,  2, -1,  2,
        -1, -1,  2,  0]),
 array([ 0,  0, -1,  0,  1,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  1, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,
         0, -1, -1,  0,  0,  0,  0,  0,  0,  1,  1, -1,  0,  0,  0,  0, -1,
        -1]),
 array([ 0, -1,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0,  0,  1, -1,  0,
         0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  1,  0]),
 array

In [89]:
from scipy.stats import itemfreq
print('hdbscan')
for each in hdb_cluster_assignment_all:
  print('#clusters:', len(np.unique(each)),' ',"#sentences in each cluster:",itemfreq(each)[:,1])
  print()

hdbscan
#clusters: 3   #sentences in each cluster: [13  2  2]

#clusters: 4   #sentences in each cluster: [16  4 21  2]

#clusters: 5   #sentences in each cluster: [28  3  3 35  3]

#clusters: 3   #sentences in each cluster: [11 36  5]

#clusters: 3   #sentences in each cluster: [ 5 24  3]

#clusters: 3   #sentences in each cluster: [  4 153   4]

#clusters: 3   #sentences in each cluster: [ 29 142   3]

#clusters: 3   #sentences in each cluster: [ 4  2 51]

#clusters: 5   #sentences in each cluster: [43  4  4 23  7]

#clusters: 4   #sentences in each cluster: [40  5  3  3]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  after removing the cwd from sys.path.


In [90]:
print('kmeans')
for each in cluster_assignment_all:
  print('#clusters:', len(np.unique(each)),' ',"#sentences in each cluster:",itemfreq(each)[:,1])
  print()

kmeans
#clusters: 2   #sentences in each cluster: [12  5]

#clusters: 2   #sentences in each cluster: [14 29]

#clusters: 2   #sentences in each cluster: [31 41]

#clusters: 2   #sentences in each cluster: [38 14]

#clusters: 2   #sentences in each cluster: [ 6 26]

#clusters: 2   #sentences in each cluster: [117  44]

#clusters: 2   #sentences in each cluster: [ 71 103]

#clusters: 5   #sentences in each cluster: [14 21 11  4  7]

#clusters: 2   #sentences in each cluster: [52 29]

#clusters: 2   #sentences in each cluster: [30 21]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  This is separate from the ipykernel package so we can avoid doing imports until


In [79]:
sentences = sent_tokenize(train_doc[7])
clustered_sentences = [[] for i in range(hdb_num_cluster_all[7])]
for sentence_id, cluster_id in enumerate(hdb_cluster_assignment_all[7]):
    clustered_sentences[cluster_id].append(sentences[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['WARCZone is a collection of outsider-uploaded WARCs, which are contributed to the Internet Archive but may or may not be ingested into the Wayback Machine.', 'They are being kept in this location for reference and clarity for the Wayback Team, while also being accessible to the general public who are seeking any particular items they can regarding certain websites.']

Cluster  2
['||||| November 21, 2016 \n \n An Open Letter to Local and State Educational Agencies & Policymakers: \n \n On behalf of the National Women’s Law Center and the undersigned organizations and individuals, we call on local, state, and federal policymakers to address the damaging use of corporal punishment against our nation’s schoolchildren.', 'It is important to eliminate the use of corporal punishment in both public schools and private schools, which serve students receiving federal services, as well as assist in creating a safer learning environment for every child.', 'Instead, we urge policymake

In [76]:
hdb_score = []
for i in range(10):
  embedding = embedding_all[i]
  hdb_score.append(metrics.silhouette_score(embedding,hdb_cluster_assignment_all[i],metric="euclidean"))
hdb_score

[-0.05343926,
 0.11482736,
 0.039849307,
 0.08770604,
 0.15276217,
 0.08105399,
 0.021959169,
 0.106905915,
 0.032575898,
 -0.029677557]

Kmeans

In [62]:
from sklearn.cluster import KMeans
num_clusters = 2
clustering_model = KMeans(n_clusters=num_clusters)
clustering_model.fit(embedding)
cluster_assignment = clustering_model.labels_

In [63]:
clustered_sentences = [[] for i in range(num_clusters)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
    clustered_sentences[cluster_id].append(sentences[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

IndexError: ignored

Silhouette score selection

In [18]:
import sklearn.metrics as metrics
import numpy as np
score = []
cluster = np.arange(2,6)
print(cluster)
for i in range(2,6):
    labels=KMeans(n_clusters=i).fit(embedding).labels_ #,init="k-means++",random_state=200
    score.append(metrics.silhouette_score(embedding,labels,metric="euclidean"))
num_clusters = cluster[np.argmax(np.array(score))]
clustering_model = KMeans(n_clusters=num_clusters)
clustering_model.fit(embedding)
cluster_assignment = clustering_model.labels_

[2 3 4 5]


In [19]:
clustered_sentences = [[] for i in range(num_clusters)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
    clustered_sentences[cluster_id].append(sentences[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['National Archives \n \n Yes, it’s that time again, folks.', 'Here at MarketBeat HQ, we’ll be offering color commentary before and after the data crosses the wires.', 'Feel free to weigh-in yourself, via the comments section.', 'And while you’re here, why don’t you sign up to follow us on Twitter.', 'Enjoy the show.', 'The official unemployment tally only includes those seeking work.']

Cluster  2
['It’s the first Friday of the month, when for one ever-so-brief moment the interests of Wall Street, Washington and Main Street are all aligned on one thing: Jobs.', 'A fresh update on the U.S. employment situation for January hits the wires at 8:30 a.m. New York time offering one of the most important snapshots on how the economy fared during the previous month.', 'Expectations are for 203,000 new jobs to be created, according to economists polled by Dow Jones Newswires, compared to 227,000 jobs added in February.', 'The unemployment rate is expected to hold steady at 8.3%.', '|

In [20]:
cluster_assignment

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int32)

In [21]:
metrics.calinski_harabasz_score(embedding, cluster_assignment)

4.754089242339544

Run 1000 rows

In [64]:
embedding_all = []
for r in range(10):
  sentences = sent_tokenize(train_doc[r]) #split sentences
  embedding = []
  for sentence in sentences:
    embedding.append(model.encode(sentence, device='cuda')) #get embedding 
  embedding_all.append(embedding)

In [65]:
num_cluster_all = []
cluster_assignment_all = []
silhouette_score_all = []
for r in range(10):
  sentences = sent_tokenize(train_doc[r]) #split sentences
  embedding = embedding_all[r] #get embedding 
  score = []
  cluster = np.arange(2,6)
  for i in range(2,6): # get best num_clusters from silhouette score
    labels=KMeans(n_clusters=i).fit(embedding).labels_ #,init="k-means++",random_state=200
    score.append(metrics.silhouette_score(embedding,labels,metric="euclidean"))
  silhouette_score_all.append(np.max(score))
  num_clusters = cluster[np.argmax(np.array(score))]
  clustering_model = KMeans(n_clusters=num_clusters)
  clustering_model.fit(embedding)
  cluster_assignment = clustering_model.labels_
  num_cluster_all.append(num_clusters)
  cluster_assignment_all.append(cluster_assignment)

In [66]:
num_cluster_all

[2, 2, 2, 2, 2, 2, 2, 5, 2, 2]

In [67]:
cluster_assignment_all

[array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1],
       dtype=int32),
 array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 0], dtype=int32),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0], dtype=int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 

In [68]:
silhouette_score_all

[0.20421648,
 0.1837118,
 0.13344246,
 0.21906878,
 0.21459319,
 0.15256447,
 0.14536247,
 0.11330531,
 0.15207909,
 0.14739855]

In [41]:
sentences = sent_tokenize(train_doc[7])
clustered_sentences = [[] for i in range(num_cluster_all[7])]
for sentence_id, cluster_id in enumerate(cluster_assignment_all[7]):
    clustered_sentences[cluster_id].append(sentences[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['More than 109,000 students were subjected to corporal punishment in public schools in the 2013-14 school year —down from 163,333 in the 2011-12 school year.', 'In seven states in which corporal punishment was legal in the 2011-12 school year, Black children were three to five times more likely to be corporally punished than white students.', 'Similarly, in several states in the 2011-12 school year, students with disabilities were over five times more likely to experience corporal punishment than students without disabilities.', 'More than 110,000 students, including disproportionate numbers of black and disabled students, were subjected to paddling or a similar punishment in the 2013-14 school year, said King, citing the Education Department’s Civil Rights Data Collection.', 'Recent research suggests that more than 160,000 children in 19 states are potential victims of corporal punishment in schools each year, with African-American children in a few southern school distric

In [91]:
s = ['It’s the first Friday of the month, when for one ever-so-brief moment the interests of Wall Street, Washington and Main Street are all aligned on one thing: Jobs.', 'A fresh update on the U.S. employment situation for January hits the wires at 8:30 a.m. New York time offering one of the most important snapshots on how the economy fared during the previous month.', 'Expectations are for 203,000 new jobs to be created, according to economists polled by Dow Jones Newswires, compared to 227,000 jobs added in February.', 'The unemployment rate is expected to hold steady at 8.3%.', '||||| Employers pulled back sharply on hiring last month, a reminder that the U.S. economy may not be growing fast enough to sustain robust job growth.', 'The unemployment rate dipped, but mostly because more Americans stopped looking for work.', 'The Labor Department says the economy added 120,000 jobs in March, down from more than 200,000 in each of the previous three months.', 'The unemployment rate fell to 8.2 percent, the lowest since January 2009.', 'The rate dropped because fewer people searched for jobs.', 'The economy has added 858,000 jobs since December _ the best four months of hiring in two years.', 'But Federal Reserve Chairman Ben Bernanke has cautioned that the current hiring pace is unlikely to continue without more consumer spending.']

In [97]:
embedding = []
for sentence in s:
  embedding.append(model.encode(sentence, device='cuda')) #get embedding 
score = []
for t in range(2,6):
  labels=KMeans(n_clusters=t).fit(embedding).labels_ #,init="k-means++",random_state=200
  score.append(metrics.silhouette_score(embedding,labels,metric="euclidean"))
num_clusters = cluster[np.argmax(np.array(score))]
clustering_model = KMeans(n_clusters=num_clusters)
clustering_model.fit(embedding)
cluster_assignment = clustering_model.labels_

In [99]:
clustered_sentences = [[] for i in range(num_clusters)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
    clustered_sentences[cluster_id].append(s[sentence_id])

for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['Expectations are for 203,000 new jobs to be created, according to economists polled by Dow Jones Newswires, compared to 227,000 jobs added in February.', 'The Labor Department says the economy added 120,000 jobs in March, down from more than 200,000 in each of the previous three months.', 'The economy has added 858,000 jobs since December _ the best four months of hiring in two years.']

Cluster  2
['The unemployment rate is expected to hold steady at 8.3%.', 'The unemployment rate fell to 8.2 percent, the lowest since January 2009.']

Cluster  3
['It’s the first Friday of the month, when for one ever-so-brief moment the interests of Wall Street, Washington and Main Street are all aligned on one thing: Jobs.', 'A fresh update on the U.S. employment situation for January hits the wires at 8:30 a.m. New York time offering one of the most important snapshots on how the economy fared during the previous month.']

Cluster  4
['The unemployment rate dipped, but mostly because mo

In [100]:
metrics.silhouette_score(embedding,cluster_assignment,metric="euclidean")

0.18705744